services:

  finovatech-gateway-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true

  finovatech-gateway-pagamento:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true

  finovatech-processador-pagamento:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true

  finovatech-deteccao-fraude:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true

  finovatech-servico-notificacao:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true

  finovatech-servico-catalogo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true

  novamart-frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
