apiVersion: v1
kind: Secret
metadata:
  name: finovatech-secrets
  namespace: finovatech
type: Opaque
stringData:
  RabbitMQ__Password: "finovatech123"
  ConnectionStrings__Pagamentos: "Host=finovatech-postgres;Database=finovatech_pagamentos;Username=finovatech;Password=finovatech123"
  Jwt__ChaveSecreta: "finovatech-super-secret-key-2026-production!"
